### ISSUE TITLE
redigo依赖问题

### ISSUE THREAD

**Issue by wgjas2** [hb-go/echo-web#11]
编译失败，错误: “pkg\mod\github.com\garyburd\redigo@v2.0.0+incompatible\redis\pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed”

经查原因如下: 
redigo已经移到新地址: github.com/gomodule/redigo
但是middleware/cache/redis.go引用的还是旧库: github.com/garyburd/redigo

**Comment by hb-chen** [comment]
github.com/garyburd/redigo@v2.0.0是依赖了github.com/gomodule/redigo，可以换用1.6版本
或者加上github.com/gomodule/redigo的包“glide get github.com/gomodule/redigo”看下

**Comment by wgjas2** [comment]
现在是用go1.11.1和1.11带的go module管理依赖，回不去了，我暂时把代码复制到本地改依赖编译

**Comment by hb-chen** [comment]
module也一样，只要把github.com/gomodule/redigo的依赖加进来就ok了
module我还没试过😂

**Comment by wgjas2** [comment]
> module也一样，只要把github.com/gomodule/redigo的依赖加进来就ok了
> module我还没试过😂

我尝试过没用，go module太智能了，认准import，两个依赖都会被自动加入，然后依然报错😂

**Comment by hb-chen** [comment]
> “pkg\mod\github.com\garyburd\redigo@v2.0.0+incompatible\redis\pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed”

问题在这，在garyburd\redigo用gomodule/redigo的internal包是有问题的，用1.6吧！

**Comment by wgjas2** [comment]
> > “pkg\mod\github.com\garyburd\redigo@v2.0.0+incompatible\redis\pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed”
> 
> 问题不在module的依赖管理，在internal包，garyburd\redigo引用gomodule/redigo的internal包是有问题的，用1.6吧！

这我是知道的，不过不想回1.6了，先本地用着吧
