### ISSUE TITLE
 dep ensure error

### ISSUE THREAD

**Issue by mxfj** [hb-go/echo-web#9]
[root]# dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  ✗  github.com/hb-go/echo-mw
  ✗  github.com/shurcooL/vfsgen
  ✗  github.com/valyala/bytebufferpool
  ✗  golang.org/x/sys

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

Solving failure: 
	(1) failed to list versions for https://go.googlesource.com/sys: error: Couldn't resolve host 'go.googlesource.com' while accessing https://go.googlesource.com/sys/info/refs

fatal: HTTP request failed
: exit status 128

**Comment by hb-chen** [comment]
更新下代码，改用glide做管理了，对golang.org/x的处理要方便些

**Comment by yuvista** [comment]
@hb-chen dep 感觉还不能在生产里用，我们也是临时自己改到了glide

**Comment by hb-chen** [comment]
恩，我也又换回来了，glide的mirror处理GFW问题还是挺方便，dep的整半天没对，看到有人fork过dep的版本进行了优化，还是算了用glide吧
